import { CuEvent, CuPackage, PaymentRecord } from '../../types';

// ── CU Events ──────────────────────────────────────────────────────────────
export const INITIAL_CU_EVENTS: CuEvent[] = [
  {
    id: 'evt-001',
    eventName: 'SIGNUP_BONUS',
    cuCost: 500,
    category: 'BONUS',
    description: 'Welcome bonus credited to new user on first registration.',
    status: 'ACTIVE',
    createdDate: '2025-01-01',
  },
  {
    id: 'evt-002',
    eventName: 'START_BOT',
    cuCost: -5,
    category: 'SPEND',
    description: 'CU deducted each time a trading bot is started or restarted.',
    status: 'ACTIVE',
    createdDate: '2025-01-01',
  },
  {
    id: 'evt-003',
    eventName: 'CYCLE_START',
    cuCost: -3,
    category: 'SPEND',
    description: 'CU deducted at the beginning of each new trading cycle.',
    status: 'ACTIVE',
    createdDate: '2025-01-01',
  },
  {
    id: 'evt-004',
    eventName: 'DCA_EXECUTED',
    cuCost: -2,
    category: 'SPEND',
    description: 'CU deducted when a DCA (Dollar Cost Average) safety order is placed.',
    status: 'ACTIVE',
    createdDate: '2025-01-01',
  },
  {
    id: 'evt-005',
    eventName: 'SELL_EXECUTED',
    cuCost: -2,
    category: 'SPEND',
    description: 'CU deducted when a take-profit or sell order is executed.',
    status: 'ACTIVE',
    createdDate: '2025-01-01',
  },
  {
    id: 'evt-006',
    eventName: 'ADD_SUB_BALANCE',
    cuCost: 0,
    category: 'SYSTEM',
    description: 'System event for manual CU balance adjustment by administrator.',
    status: 'ACTIVE',
    createdDate: '2025-01-01',
  },
  {
    id: 'evt-007',
    eventName: 'REFERRAL_BONUS',
    cuCost: 200,
    category: 'BONUS',
    description: 'CU reward credited when a referred user completes first purchase.',
    status: 'ACTIVE',
    createdDate: '2025-01-15',
  },
  {
    id: 'evt-008',
    eventName: 'API_ERROR_REFUND',
    cuCost: 0,
    category: 'SYSTEM',
    description: 'Variable CU refund issued when exchange API error causes unintended deduction.',
    status: 'ACTIVE',
    createdDate: '2025-02-01',
  },
  {
    id: 'evt-009',
    eventName: 'GRID_REBALANCE',
    cuCost: -1,
    category: 'SPEND',
    description: 'CU deducted each time a grid bot rebalances its price levels.',
    status: 'ACTIVE',
    createdDate: '2025-03-10',
  },
  {
    id: 'evt-010',
    eventName: 'TRAILING_ADJUST',
    cuCost: -1,
    category: 'SPEND',
    description: 'CU deducted when trailing stop or trailing entry is adjusted.',
    status: 'ACTIVE',
    createdDate: '2025-03-10',
  },
  {
    id: 'evt-011',
    eventName: 'DAILY_BONUS',
    cuCost: 50,
    category: 'BONUS',
    description: 'Daily login reward for active users (feature pending activation).',
    status: 'INACTIVE',
    createdDate: '2025-05-01',
  },
  {
    id: 'evt-012',
    eventName: 'ANOMALY_DETECTED',
    cuCost: 0,
    category: 'SYSTEM',
    description: 'System event logged when bot enters ANOMALY state — no CU charged.',
    status: 'ACTIVE',
    createdDate: '2025-04-20',
  },
];

// ── CU Packages ───────────────────────────────────────────────────────────
export const INITIAL_CU_PACKAGES: CuPackage[] = [
  {
    id: 'pkg-001',
    name: 'Starter Pack',
    cuAmount: 1000,
    priceUsd: 9.99,
    discountPercent: 0,
    status: 'ACTIVE',
    createdDate: '2025-01-01',
  },
  {
    id: 'pkg-002',
    name: 'Basic Pack',
    cuAmount: 3000,
    priceUsd: 24.99,
    discountPercent: 0,
    status: 'ACTIVE',
    createdDate: '2025-01-01',
  },
  {
    id: 'pkg-003',
    name: 'Pro Pack',
    cuAmount: 10000,
    priceUsd: 79.99,
    discountPercent: 10,
    status: 'ACTIVE',
    badge: 'POPULAR',
    createdDate: '2025-01-01',
  },
  {
    id: 'pkg-004',
    name: 'VIP Bundle',
    cuAmount: 25000,
    priceUsd: 179.99,
    discountPercent: 20,
    status: 'ACTIVE',
    badge: 'BEST VALUE',
    createdDate: '2025-01-01',
  },
  {
    id: 'pkg-005',
    name: 'Enterprise Pack',
    cuAmount: 100000,
    priceUsd: 599.99,
    discountPercent: 30,
    status: 'ACTIVE',
    badge: 'ENTERPRISE',
    createdDate: '2025-06-01',
  },
  {
    id: 'pkg-006',
    name: 'Legacy Pack',
    cuAmount: 5000,
    priceUsd: 49.99,
    discountPercent: 0,
    status: 'INACTIVE',
    createdDate: '2024-06-01',
  },
];

// ── Payments (full list with packageId/packageName) ────────────────────────
export const MOCK_SUB_PAYMENTS: PaymentRecord[] = [
  { id: 'pay-772', username: '@cryptodan88',    packageId: 'pkg-004', packageName: 'VIP Bundle',      timestamp: '2026-05-28 09:12', amountUsd: 179.99, cuCredited: 25000, method: 'Crypto Pay (USDT_TRC20)', status: 'SUCCESS' },
  { id: 'pay-651', username: '@cryptodan88',    packageId: 'pkg-002', packageName: 'Basic Pack',      timestamp: '2026-04-12 11:45', amountUsd:  24.99, cuCredited:  3000, method: 'Crypto Pay (USDT_TRC20)', status: 'SUCCESS' },
  { id: 'pay-213', username: '@cryptodan88',    packageId: 'pkg-003', packageName: 'Pro Pack',        timestamp: '2026-03-30 18:22', amountUsd:  71.99, cuCredited: 10000, method: 'GatePay Crypto',          status: 'FAILED'  },
  { id: 'pay-890', username: '@johndoe_quant',  packageId: 'pkg-002', packageName: 'Basic Pack',      timestamp: '2026-05-20 14:05', amountUsd:  24.99, cuCredited:  3000, method: 'Stripe Credit Card',      status: 'SUCCESS' },
  { id: 'pay-512', username: '@johndoe_quant',  packageId: 'pkg-001', packageName: 'Starter Pack',    timestamp: '2026-04-08 09:30', amountUsd:   9.99, cuCredited:  1000, method: 'Crypto Pay (USDT_TRC20)', status: 'PENDING' },
  { id: 'pay-301', username: '@moon_scalper',   packageId: 'pkg-004', packageName: 'VIP Bundle',      timestamp: '2026-05-15 17:44', amountUsd: 179.99, cuCredited: 25000, method: 'GatePay Crypto',          status: 'SUCCESS' },
  { id: 'pay-144', username: '@hodl_pro',       packageId: 'pkg-002', packageName: 'Basic Pack',      timestamp: '2026-05-10 08:20', amountUsd:  24.99, cuCredited:  3000, method: 'Stripe Credit Card',      status: 'SUCCESS' },
  { id: 'pay-088', username: '@btc_enthusiast', packageId: 'pkg-004', packageName: 'VIP Bundle',      timestamp: '2026-04-22 21:15', amountUsd: 179.99, cuCredited: 25000, method: 'Crypto Pay (USDT_TRC20)', status: 'SUCCESS' },
  { id: 'pay-320', username: '@alice_trades',   packageId: 'pkg-002', packageName: 'Basic Pack',      timestamp: '2026-05-10 16:00', amountUsd:  24.99, cuCredited:  3000, method: 'Stripe Credit Card',      status: 'SUCCESS' },
  { id: 'pay-410', username: '@charlie_nodes',  packageId: 'pkg-003', packageName: 'Pro Pack',        timestamp: '2026-06-01 11:20', amountUsd:  71.99, cuCredited: 10000, method: 'GatePay Crypto',          status: 'SUCCESS' },
  { id: 'pay-411', username: '@charlie_nodes',  packageId: 'pkg-002', packageName: 'Basic Pack',      timestamp: '2026-05-05 08:45', amountUsd:  24.99, cuCredited:  3000, method: 'Crypto Pay (USDT_TRC20)', status: 'SUCCESS' },
  { id: 'pay-412', username: '@charlie_nodes',  packageId: 'pkg-001', packageName: 'Starter Pack',    timestamp: '2026-04-18 14:30', amountUsd:   9.99, cuCredited:  1000, method: 'Stripe Credit Card',      status: 'FAILED'  },
  { id: 'pay-610', username: '@delta_grid',     packageId: 'pkg-004', packageName: 'VIP Bundle',      timestamp: '2026-06-02 10:00', amountUsd: 179.99, cuCredited: 25000, method: 'Crypto Pay (USDT_TRC20)', status: 'SUCCESS' },
  { id: 'pay-611', username: '@delta_grid',     packageId: 'pkg-003', packageName: 'Pro Pack',        timestamp: '2026-05-15 13:30', amountUsd:  71.99, cuCredited: 10000, method: 'GatePay Crypto',          status: 'SUCCESS' },
  { id: 'pay-720', username: '@omega_trader',   packageId: 'pkg-005', packageName: 'Enterprise Pack', timestamp: '2026-06-03 08:45', amountUsd: 419.99, cuCredited:100000, method: 'Crypto Pay (USDT_TRC20)', status: 'SUCCESS' },
  { id: 'pay-721', username: '@quant_pro99',    packageId: 'pkg-003', packageName: 'Pro Pack',        timestamp: '2026-06-03 14:20', amountUsd:  71.99, cuCredited: 10000, method: 'Stripe Credit Card',      status: 'SUCCESS' },
  { id: 'pay-722', username: '@grid_master',    packageId: 'pkg-004', packageName: 'VIP Bundle',      timestamp: '2026-06-04 07:10', amountUsd: 179.99, cuCredited: 25000, method: 'GatePay Crypto',          status: 'PENDING' },
  { id: 'pay-723', username: '@dca_daily',      packageId: 'pkg-001', packageName: 'Starter Pack',    timestamp: '2026-06-04 09:30', amountUsd:   9.99, cuCredited:  1000, method: 'Stripe Credit Card',      status: 'SUCCESS' },
];
